package tushu.model;

import java.io.Serializable;

public class AddressMessageDO implements Serializable {
    
	private static final long serialVersionUID = -7545880331170081898L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address_message.id
     *
     * @mbggenerated Wed Sep 18 10:21:12 CST 2013
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address_message.user_Id
     *
     * @mbggenerated Wed Sep 18 10:21:12 CST 2013
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address_message.order_Form_Id
     *
     * @mbggenerated Wed Sep 18 10:21:12 CST 2013
     */
    private Long orderFormId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address_message.recipients_Name
     *
     * @mbggenerated Wed Sep 18 10:21:12 CST 2013
     */
    private String recipientsName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address_message.province
     *
     * @mbggenerated Wed Sep 18 10:21:12 CST 2013
     */
    private String province;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address_message.city
     *
     * @mbggenerated Wed Sep 18 10:21:12 CST 2013
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address_message.county
     *
     * @mbggenerated Wed Sep 18 10:21:12 CST 2013
     */
    private String county;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address_message.street
     *
     * @mbggenerated Wed Sep 18 10:21:12 CST 2013
     */
    private String street;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address_message.phone
     *
     * @mbggenerated Wed Sep 18 10:21:12 CST 2013
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address_message.tel
     *
     * @mbggenerated Wed Sep 18 10:21:12 CST 2013
     */
    private String tel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address_message.email
     *
     * @mbggenerated Wed Sep 18 10:21:12 CST 2013
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address_message.post_Code
     *
     * @mbggenerated Wed Sep 18 10:21:12 CST 2013
     */
    private String postCode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address_message.id
     *
     * @return the value of address_message.id
     *
     * @mbggenerated Wed Sep 18 10:21:12 CST 2013
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address_message.id
     *
     * @param id the value for address_message.id
     *
     * @mbggenerated Wed Sep 18 10:21:12 CST 2013
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address_message.user_Id
     *
     * @return the value of address_message.user_Id
     *
     * @mbggenerated Wed Sep 18 10:21:12 CST 2013
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address_message.user_Id
     *
     * @param userId the value for address_message.user_Id
     *
     * @mbggenerated Wed Sep 18 10:21:12 CST 2013
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address_message.order_Form_Id
     *
     * @return the value of address_message.order_Form_Id
     *
     * @mbggenerated Wed Sep 18 10:21:12 CST 2013
     */
    public Long getOrderFormId() {
        return orderFormId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address_message.order_Form_Id
     *
     * @param orderFormId the value for address_message.order_Form_Id
     *
     * @mbggenerated Wed Sep 18 10:21:12 CST 2013
     */
    public void setOrderFormId(Long orderFormId) {
        this.orderFormId = orderFormId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address_message.recipients_Name
     *
     * @return the value of address_message.recipients_Name
     *
     * @mbggenerated Wed Sep 18 10:21:12 CST 2013
     */
    public String getRecipientsName() {
        return recipientsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address_message.recipients_Name
     *
     * @param recipientsName the value for address_message.recipients_Name
     *
     * @mbggenerated Wed Sep 18 10:21:12 CST 2013
     */
    public void setRecipientsName(String recipientsName) {
        this.recipientsName = recipientsName == null ? null : recipientsName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address_message.province
     *
     * @return the value of address_message.province
     *
     * @mbggenerated Wed Sep 18 10:21:12 CST 2013
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address_message.province
     *
     * @param province the value for address_message.province
     *
     * @mbggenerated Wed Sep 18 10:21:12 CST 2013
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address_message.city
     *
     * @return the value of address_message.city
     *
     * @mbggenerated Wed Sep 18 10:21:12 CST 2013
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address_message.city
     *
     * @param city the value for address_message.city
     *
     * @mbggenerated Wed Sep 18 10:21:12 CST 2013
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address_message.county
     *
     * @return the value of address_message.county
     *
     * @mbggenerated Wed Sep 18 10:21:12 CST 2013
     */
    public String getCounty() {
        return county;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address_message.county
     *
     * @param county the value for address_message.county
     *
     * @mbggenerated Wed Sep 18 10:21:12 CST 2013
     */
    public void setCounty(String county) {
        this.county = county == null ? null : county.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address_message.street
     *
     * @return the value of address_message.street
     *
     * @mbggenerated Wed Sep 18 10:21:12 CST 2013
     */
    public String getStreet() {
        return street;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address_message.street
     *
     * @param street the value for address_message.street
     *
     * @mbggenerated Wed Sep 18 10:21:12 CST 2013
     */
    public void setStreet(String street) {
        this.street = street == null ? null : street.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address_message.phone
     *
     * @return the value of address_message.phone
     *
     * @mbggenerated Wed Sep 18 10:21:12 CST 2013
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address_message.phone
     *
     * @param phone the value for address_message.phone
     *
     * @mbggenerated Wed Sep 18 10:21:12 CST 2013
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address_message.tel
     *
     * @return the value of address_message.tel
     *
     * @mbggenerated Wed Sep 18 10:21:12 CST 2013
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address_message.tel
     *
     * @param tel the value for address_message.tel
     *
     * @mbggenerated Wed Sep 18 10:21:12 CST 2013
     */
    public void setTel(String tel) {
        this.tel = tel == null ? null : tel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address_message.email
     *
     * @return the value of address_message.email
     *
     * @mbggenerated Wed Sep 18 10:21:12 CST 2013
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address_message.email
     *
     * @param email the value for address_message.email
     *
     * @mbggenerated Wed Sep 18 10:21:12 CST 2013
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address_message.post_Code
     *
     * @return the value of address_message.post_Code
     *
     * @mbggenerated Wed Sep 18 10:21:12 CST 2013
     */
    public String getPostCode() {
        return postCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address_message.post_Code
     *
     * @param postCode the value for address_message.post_Code
     *
     * @mbggenerated Wed Sep 18 10:21:12 CST 2013
     */
    public void setPostCode(String postCode) {
        this.postCode = postCode == null ? null : postCode.trim();
    }
}