package tushu.model;

import java.io.Serializable;

public class ExpressMessageDO implements Serializable {
	
	private static final long serialVersionUID = 1175538446507304414L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column express_message.id
     *
     * @mbggenerated Thu Sep 26 10:37:52 CST 2013
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column express_message.express_Name
     *
     * @mbggenerated Thu Sep 26 10:37:52 CST 2013
     */
    private String expressName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column express_message.express_Price
     *
     * @mbggenerated Thu Sep 26 10:37:52 CST 2013
     */
    private Double expressPrice;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column express_message.id
     *
     * @return the value of express_message.id
     *
     * @mbggenerated Thu Sep 26 10:37:52 CST 2013
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column express_message.id
     *
     * @param id the value for express_message.id
     *
     * @mbggenerated Thu Sep 26 10:37:52 CST 2013
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column express_message.express_Name
     *
     * @return the value of express_message.express_Name
     *
     * @mbggenerated Thu Sep 26 10:37:52 CST 2013
     */
    public String getExpressName() {
        return expressName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column express_message.express_Name
     *
     * @param expressName the value for express_message.express_Name
     *
     * @mbggenerated Thu Sep 26 10:37:52 CST 2013
     */
    public void setExpressName(String expressName) {
        this.expressName = expressName == null ? null : expressName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column express_message.express_Price
     *
     * @return the value of express_message.express_Price
     *
     * @mbggenerated Thu Sep 26 10:37:52 CST 2013
     */
    public Double getExpressPrice() {
        return expressPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column express_message.express_Price
     *
     * @param expressPrice the value for express_message.express_Price
     *
     * @mbggenerated Thu Sep 26 10:37:52 CST 2013
     */
    public void setExpressPrice(Double expressPrice) {
        this.expressPrice = expressPrice;
    }
}