package tushu.model;

import java.io.Serializable;

public class IndexShowTypeDO implements Serializable {
  
	private static final long serialVersionUID = 9066605682852226023L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column index_show_type.id
     *
     * @mbggenerated Tue Sep 10 10:18:11 CST 2013
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column index_show_type.name
     *
     * @mbggenerated Tue Sep 10 10:18:11 CST 2013
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column index_show_type.describe
     *
     * @mbggenerated Tue Sep 10 10:18:11 CST 2013
     */
    private String describe;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column index_show_type.type
     *
     * @mbggenerated Tue Sep 10 10:18:11 CST 2013
     */
    private String type;

    private Integer index;
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column index_show_type.id
     *
     * @return the value of index_show_type.id
     *
     * @mbggenerated Tue Sep 10 10:18:11 CST 2013
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column index_show_type.id
     *
     * @param id the value for index_show_type.id
     *
     * @mbggenerated Tue Sep 10 10:18:11 CST 2013
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column index_show_type.name
     *
     * @return the value of index_show_type.name
     *
     * @mbggenerated Tue Sep 10 10:18:11 CST 2013
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column index_show_type.name
     *
     * @param name the value for index_show_type.name
     *
     * @mbggenerated Tue Sep 10 10:18:11 CST 2013
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column index_show_type.describe
     *
     * @return the value of index_show_type.describe
     *
     * @mbggenerated Tue Sep 10 10:18:11 CST 2013
     */
    public String getDescribe() {
        return describe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column index_show_type.describe
     *
     * @param describe the value for index_show_type.describe
     *
     * @mbggenerated Tue Sep 10 10:18:11 CST 2013
     */
    public void setDescribe(String describe) {
        this.describe = describe == null ? null : describe.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column index_show_type.type
     *
     * @return the value of index_show_type.type
     *
     * @mbggenerated Tue Sep 10 10:18:11 CST 2013
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column index_show_type.type
     *
     * @param type the value for index_show_type.type
     *
     * @mbggenerated Tue Sep 10 10:18:11 CST 2013
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

	public Integer getIndex() {
		return index;
	}

	public void setIndex(Integer index) {
		this.index = index;
	}
}