package tushu.model;

import java.io.Serializable;
import java.util.Date;

public class OrderFormDO implements Serializable {
	
	private static final long serialVersionUID = 6653986341648063394L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_form.id
     *
     * @mbggenerated Sun Sep 15 15:26:33 CST 2013
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_form.order_Number
     *
     * @mbggenerated Sun Sep 15 15:26:33 CST 2013
     */
    private String orderNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_form.user_Id
     *
     * @mbggenerated Sun Sep 15 15:26:33 CST 2013
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_form.product_Id
     *
     * @mbggenerated Sun Sep 15 15:26:33 CST 2013
     */
    private Integer productId;

    private Integer workId;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_form.create_Time
     *
     * @mbggenerated Sun Sep 15 15:26:33 CST 2013
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_form.payment_Time
     *
     * @mbggenerated Sun Sep 15 15:26:33 CST 2013
     */
    private Date paymentTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_form.order_Type
     *
     * @mbggenerated Sun Sep 15 15:26:33 CST 2013
     */
    private String orderType;

    private Integer productNumber;

    private Double amountPayable;
    
    private Integer expressMessage;
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_form.id
     *
     * @return the value of order_form.id
     *
     * @mbggenerated Sun Sep 15 15:26:33 CST 2013
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_form.id
     *
     * @param id the value for order_form.id
     *
     * @mbggenerated Sun Sep 15 15:26:33 CST 2013
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_form.order_Number
     *
     * @return the value of order_form.order_Number
     *
     * @mbggenerated Sun Sep 15 15:26:33 CST 2013
     */
    public String getOrderNumber() {
        return orderNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_form.order_Number
     *
     * @param orderNumber the value for order_form.order_Number
     *
     * @mbggenerated Sun Sep 15 15:26:33 CST 2013
     */
    public void setOrderNumber(String orderNumber) {
        this.orderNumber = orderNumber == null ? null : orderNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_form.user_Id
     *
     * @return the value of order_form.user_Id
     *
     * @mbggenerated Sun Sep 15 15:26:33 CST 2013
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_form.user_Id
     *
     * @param userId the value for order_form.user_Id
     *
     * @mbggenerated Sun Sep 15 15:26:33 CST 2013
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_form.product_Id
     *
     * @return the value of order_form.product_Id
     *
     * @mbggenerated Sun Sep 15 15:26:33 CST 2013
     */
    public Integer getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_form.product_Id
     *
     * @param productId the value for order_form.product_Id
     *
     * @mbggenerated Sun Sep 15 15:26:33 CST 2013
     */
    public void setProductId(Integer productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_form.create_Time
     *
     * @return the value of order_form.create_Time
     *
     * @mbggenerated Sun Sep 15 15:26:33 CST 2013
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_form.create_Time
     *
     * @param createTime the value for order_form.create_Time
     *
     * @mbggenerated Sun Sep 15 15:26:33 CST 2013
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_form.payment_Time
     *
     * @return the value of order_form.payment_Time
     *
     * @mbggenerated Sun Sep 15 15:26:33 CST 2013
     */
    public Date getPaymentTime() {
        return paymentTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_form.payment_Time
     *
     * @param paymentTime the value for order_form.payment_Time
     *
     * @mbggenerated Sun Sep 15 15:26:33 CST 2013
     */
    public void setPaymentTime(Date paymentTime) {
        this.paymentTime = paymentTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_form.order_Type
     *
     * @return the value of order_form.order_Type
     *
     * @mbggenerated Sun Sep 15 15:26:33 CST 2013
     */
    public String getOrderType() {
        return orderType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_form.order_Type
     *
     * @param orderType the value for order_form.order_Type
     *
     * @mbggenerated Sun Sep 15 15:26:33 CST 2013
     */
    public void setOrderType(String orderType) {
        this.orderType = orderType == null ? null : orderType.trim();
    }

	public Integer getProductNumber() {
		return productNumber;
	}

	public void setProductNumber(Integer productNumber) {
		this.productNumber = productNumber;
	}

	public Double getAmountPayable() {
		return amountPayable;
	}

	public void setAmountPayable(Double amountPayable) {
		this.amountPayable = amountPayable;
	}

	public Integer getExpressMessage() {
		return expressMessage;
	}

	public void setExpressMessage(Integer expressMessage) {
		this.expressMessage = expressMessage;
	}

	public Integer getWorkId() {
		return workId;
	}

	public void setWorkId(Integer workId) {
		this.workId = workId;
	}
}