package tushu.model;

import java.io.Serializable;

public class PageDO implements Serializable {
    
	private static final long serialVersionUID = 4860757608061457941L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column page_message.id
     *
     * @mbggenerated Thu Nov 07 15:46:39 CST 2013
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column page_message.page_Num
     *
     * @mbggenerated Thu Nov 07 15:46:39 CST 2013
     */
    private Integer pageNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column page_message.page_Type
     *
     * @mbggenerated Thu Nov 07 15:46:39 CST 2013
     */
    private String pageType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column page_message.template_Id
     *
     * @mbggenerated Thu Nov 07 15:46:39 CST 2013
     */
    private Integer templateId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column page_message.work_Id
     *
     * @mbggenerated Thu Nov 07 15:46:39 CST 2013
     */
    private Integer workId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column page_message.page-desc
     *
     * @mbggenerated Thu Nov 07 15:46:39 CST 2013
     */
    private String pageDesc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column page_message.id
     *
     * @return the value of page_message.id
     *
     * @mbggenerated Thu Nov 07 15:46:39 CST 2013
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column page_message.id
     *
     * @param id the value for page_message.id
     *
     * @mbggenerated Thu Nov 07 15:46:39 CST 2013
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column page_message.page_Num
     *
     * @return the value of page_message.page_Num
     *
     * @mbggenerated Thu Nov 07 15:46:39 CST 2013
     */
    public Integer getPageNum() {
        return pageNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column page_message.page_Num
     *
     * @param pageNum the value for page_message.page_Num
     *
     * @mbggenerated Thu Nov 07 15:46:39 CST 2013
     */
    public void setPageNum(Integer pageNum) {
        this.pageNum = pageNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column page_message.page_Type
     *
     * @return the value of page_message.page_Type
     *
     * @mbggenerated Thu Nov 07 15:46:39 CST 2013
     */
    public String getPageType() {
        return pageType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column page_message.page_Type
     *
     * @param pageType the value for page_message.page_Type
     *
     * @mbggenerated Thu Nov 07 15:46:39 CST 2013
     */
    public void setPageType(String pageType) {
        this.pageType = pageType == null ? null : pageType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column page_message.template_Id
     *
     * @return the value of page_message.template_Id
     *
     * @mbggenerated Thu Nov 07 15:46:39 CST 2013
     */
    public Integer getTemplateId() {
        return templateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column page_message.template_Id
     *
     * @param templateId the value for page_message.template_Id
     *
     * @mbggenerated Thu Nov 07 15:46:39 CST 2013
     */
    public void setTemplateId(Integer templateId) {
        this.templateId = templateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column page_message.work_Id
     *
     * @return the value of page_message.work_Id
     *
     * @mbggenerated Thu Nov 07 15:46:39 CST 2013
     */
    public Integer getWorkId() {
        return workId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column page_message.work_Id
     *
     * @param workId the value for page_message.work_Id
     *
     * @mbggenerated Thu Nov 07 15:46:39 CST 2013
     */
    public void setWorkId(Integer workId) {
        this.workId = workId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column page_message.page-desc
     *
     * @return the value of page_message.page-desc
     *
     * @mbggenerated Thu Nov 07 15:46:39 CST 2013
     */
    public String getPageDesc() {
        return pageDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column page_message.page-desc
     *
     * @param pageDesc the value for page_message.page-desc
     *
     * @mbggenerated Thu Nov 07 15:46:39 CST 2013
     */
    public void setPageDesc(String pageDesc) {
        this.pageDesc = pageDesc == null ? null : pageDesc.trim();
    }
}