package tushu.model;

import java.io.Serializable;

public class ProductDO implements Serializable {
   
	private static final long serialVersionUID = 3558823188832777838L;

    private Integer productId;
    
    private Integer indexShowTypeId;

    private String name;

    private Double sellPrice;

    private Double marketPrice;

    private Integer pages;

    private Double freight;

    private String productStandard;

    private String productMaterial;

    private String productProcess;

    private String productionCycle;

    private String content1;

    private String content2;

    private String content3;

    private String content4;

    private Integer imageId;//image_Id
	
	private String indexShowImageType;//index_Show_Image_Type
	
	private Integer viewCount;
	
	private Integer saledCount;
	
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.product_Id
     *
     * @return the value of product.product_Id
     *
     * @mbggenerated Mon Sep 09 16:18:50 CST 2013
     */
    public Integer getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.product_Id
     *
     * @param productId the value for product.product_Id
     *
     * @mbggenerated Mon Sep 09 16:18:50 CST 2013
     */
    public void setProductId(Integer productId) {
        this.productId = productId;
    }

    public Integer getIndexShowTypeId() {
		return indexShowTypeId;
	}

	public void setIndexShowTypeId(Integer indexShowTypeId) {
		this.indexShowTypeId = indexShowTypeId;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.name
     *
     * @return the value of product.name
     *
     * @mbggenerated Mon Sep 09 16:18:50 CST 2013
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.name
     *
     * @param name the value for product.name
     *
     * @mbggenerated Mon Sep 09 16:18:50 CST 2013
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.sell_Price
     *
     * @return the value of product.sell_Price
     *
     * @mbggenerated Mon Sep 09 16:18:50 CST 2013
     */
    public Double getSellPrice() {
        return sellPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.sell_Price
     *
     * @param sellPrice the value for product.sell_Price
     *
     * @mbggenerated Mon Sep 09 16:18:50 CST 2013
     */
    public void setSellPrice(Double sellPrice) {
        this.sellPrice = sellPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.market_Price
     *
     * @return the value of product.market_Price
     *
     * @mbggenerated Mon Sep 09 16:18:50 CST 2013
     */
    public Double getMarketPrice() {
        return marketPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.market_Price
     *
     * @param marketPrice the value for product.market_Price
     *
     * @mbggenerated Mon Sep 09 16:18:50 CST 2013
     */
    public void setMarketPrice(Double marketPrice) {
        this.marketPrice = marketPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.pages
     *
     * @return the value of product.pages
     *
     * @mbggenerated Mon Sep 09 16:18:50 CST 2013
     */
    public Integer getPages() {
        return pages;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.pages
     *
     * @param pages the value for product.pages
     *
     * @mbggenerated Mon Sep 09 16:18:50 CST 2013
     */
    public void setPages(Integer pages) {
        this.pages = pages;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.freight
     *
     * @return the value of product.freight
     *
     * @mbggenerated Mon Sep 09 16:18:50 CST 2013
     */
    public Double getFreight() {
        return freight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.freight
     *
     * @param freight the value for product.freight
     *
     * @mbggenerated Mon Sep 09 16:18:50 CST 2013
     */
    public void setFreight(Double freight) {
        this.freight = freight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.product_Standard
     *
     * @return the value of product.product_Standard
     *
     * @mbggenerated Mon Sep 09 16:18:50 CST 2013
     */
    public String getProductStandard() {
        return productStandard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.product_Standard
     *
     * @param productStandard the value for product.product_Standard
     *
     * @mbggenerated Mon Sep 09 16:18:50 CST 2013
     */
    public void setProductStandard(String productStandard) {
        this.productStandard = productStandard == null ? null : productStandard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.product_Material
     *
     * @return the value of product.product_Material
     *
     * @mbggenerated Mon Sep 09 16:18:50 CST 2013
     */
    public String getProductMaterial() {
        return productMaterial;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.product_Material
     *
     * @param productMaterial the value for product.product_Material
     *
     * @mbggenerated Mon Sep 09 16:18:50 CST 2013
     */
    public void setProductMaterial(String productMaterial) {
        this.productMaterial = productMaterial == null ? null : productMaterial.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.product_Process
     *
     * @return the value of product.product_Process
     *
     * @mbggenerated Mon Sep 09 16:18:50 CST 2013
     */
    public String getProductProcess() {
        return productProcess;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.product_Process
     *
     * @param productProcess the value for product.product_Process
     *
     * @mbggenerated Mon Sep 09 16:18:50 CST 2013
     */
    public void setProductProcess(String productProcess) {
        this.productProcess = productProcess == null ? null : productProcess.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.production_Cycle
     *
     * @return the value of product.production_Cycle
     *
     * @mbggenerated Mon Sep 09 16:18:50 CST 2013
     */
    public String getProductionCycle() {
        return productionCycle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.production_Cycle
     *
     * @param productionCycle the value for product.production_Cycle
     *
     * @mbggenerated Mon Sep 09 16:18:50 CST 2013
     */
    public void setProductionCycle(String productionCycle) {
        this.productionCycle = productionCycle == null ? null : productionCycle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.content1
     *
     * @return the value of product.content1
     *
     * @mbggenerated Mon Sep 09 16:18:50 CST 2013
     */
    public String getContent1() {
        return content1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.content1
     *
     * @param content1 the value for product.content1
     *
     * @mbggenerated Mon Sep 09 16:18:50 CST 2013
     */
    public void setContent1(String content1) {
        this.content1 = content1 == null ? null : content1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.content2
     *
     * @return the value of product.content2
     *
     * @mbggenerated Mon Sep 09 16:18:50 CST 2013
     */
    public String getContent2() {
        return content2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.content2
     *
     * @param content2 the value for product.content2
     *
     * @mbggenerated Mon Sep 09 16:18:50 CST 2013
     */
    public void setContent2(String content2) {
        this.content2 = content2 == null ? null : content2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.content3
     *
     * @return the value of product.content3
     *
     * @mbggenerated Mon Sep 09 16:18:50 CST 2013
     */
    public String getContent3() {
        return content3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.content3
     *
     * @param content3 the value for product.content3
     *
     * @mbggenerated Mon Sep 09 16:18:50 CST 2013
     */
    public void setContent3(String content3) {
        this.content3 = content3 == null ? null : content3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.content4
     *
     * @return the value of product.content4
     *
     * @mbggenerated Mon Sep 09 16:18:50 CST 2013
     */
    public String getContent4() {
        return content4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.content4
     *
     * @param content4 the value for product.content4
     *
     * @mbggenerated Mon Sep 09 16:18:50 CST 2013
     */
    public void setContent4(String content4) {
        this.content4 = content4 == null ? null : content4.trim();
    }

	public Integer getIndexShowImage() {
		return imageId;
	}

	public void setIndexShowImage(Integer imageId) {
		this.imageId = imageId;
	}

	public String getIndexShowImageType() {
		return indexShowImageType;
	}

	public void setIndexShowImageType(String indexShowImageType) {
		this.indexShowImageType = indexShowImageType;
	}

	public Integer getImageId() {
		return imageId;
	}

	public void setImageId(Integer imageId) {
		this.imageId = imageId;
	}

	public Integer getViewCount() {
		return viewCount;
	}

	public void setViewCount(Integer viewCount) {
		this.viewCount = viewCount;
	}

	public Integer getSaledCount() {
		return saledCount;
	}

	public void setSaledCount(Integer saledCount) {
		this.saledCount = saledCount;
	}
}