package tushu.model;

public class WorkRelationshipImageDO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_relationship_image.id
     *
     * @mbggenerated Mon Oct 28 16:04:15 CST 2013
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_relationship_image.work_Id
     *
     * @mbggenerated Mon Oct 28 16:04:15 CST 2013
     */
    private Integer workId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_relationship_image.image_Id
     *
     * @mbggenerated Mon Oct 28 16:04:15 CST 2013
     */
    private Integer imageId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_relationship_image.id
     *
     * @return the value of work_relationship_image.id
     *
     * @mbggenerated Mon Oct 28 16:04:15 CST 2013
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_relationship_image.id
     *
     * @param id the value for work_relationship_image.id
     *
     * @mbggenerated Mon Oct 28 16:04:15 CST 2013
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_relationship_image.work_Id
     *
     * @return the value of work_relationship_image.work_Id
     *
     * @mbggenerated Mon Oct 28 16:04:15 CST 2013
     */
    public Integer getWorkId() {
        return workId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_relationship_image.work_Id
     *
     * @param workId the value for work_relationship_image.work_Id
     *
     * @mbggenerated Mon Oct 28 16:04:15 CST 2013
     */
    public void setWorkId(Integer workId) {
        this.workId = workId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_relationship_image.image_Id
     *
     * @return the value of work_relationship_image.image_Id
     *
     * @mbggenerated Mon Oct 28 16:04:15 CST 2013
     */
    public Integer getImageId() {
        return imageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_relationship_image.image_Id
     *
     * @param imageId the value for work_relationship_image.image_Id
     *
     * @mbggenerated Mon Oct 28 16:04:15 CST 2013
     */
    public void setImageId(Integer imageId) {
        this.imageId = imageId;
    }
}