package tushu.model;

public class WorkDO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_message.id
     *
     * @mbggenerated Mon Oct 28 15:52:38 CST 2013
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_message.product_Id
     *
     * @mbggenerated Mon Oct 28 15:52:38 CST 2013
     */
    private Integer productId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_message.user_Id
     *
     * @mbggenerated Mon Oct 28 15:52:38 CST 2013
     */
    private Long userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_message.id
     *
     * @return the value of work_message.id
     *
     * @mbggenerated Mon Oct 28 15:52:38 CST 2013
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_message.id
     *
     * @param id the value for work_message.id
     *
     * @mbggenerated Mon Oct 28 15:52:38 CST 2013
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_message.product_Id
     *
     * @return the value of work_message.product_Id
     *
     * @mbggenerated Mon Oct 28 15:52:38 CST 2013
     */
    public Integer getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_message.product_Id
     *
     * @param productId the value for work_message.product_Id
     *
     * @mbggenerated Mon Oct 28 15:52:38 CST 2013
     */
    public void setProductId(Integer productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_message.user_Id
     *
     * @return the value of work_message.user_Id
     *
     * @mbggenerated Mon Oct 28 15:52:38 CST 2013
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_message.user_Id
     *
     * @param userId the value for work_message.user_Id
     *
     * @mbggenerated Mon Oct 28 15:52:38 CST 2013
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }
}