package tushu.product.mapper;

import java.util.List;

import tushu.model.AddressMessageDO;

public interface AddressMessageDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table address_message
     *
     * @mbggenerated Wed Sep 18 10:21:12 CST 2013
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table address_message
     *
     * @mbggenerated Wed Sep 18 10:21:12 CST 2013
     */
    int insert(AddressMessageDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table address_message
     *
     * @mbggenerated Wed Sep 18 10:21:12 CST 2013
     */
    int insertSelective(AddressMessageDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table address_message
     *
     * @mbggenerated Wed Sep 18 10:21:12 CST 2013
     */
    AddressMessageDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table address_message
     *
     * @mbggenerated Wed Sep 18 10:21:12 CST 2013
     */
    int updateByPrimaryKeySelective(AddressMessageDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table address_message
     *
     * @mbggenerated Wed Sep 18 10:21:12 CST 2013
     */
    int updateByPrimaryKey(AddressMessageDO record);
    
    List<AddressMessageDO> getByUserId(Long userId);
    
    AddressMessageDO getByOrderFormId(Long formId);
}