package tushu.product.mapper;

import java.util.List;

import tushu.model.ExpressMessageDO;

public interface ExpressMessageDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table express_message
     *
     * @mbggenerated Thu Sep 26 10:37:52 CST 2013
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table express_message
     *
     * @mbggenerated Thu Sep 26 10:37:52 CST 2013
     */
    int insert(ExpressMessageDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table express_message
     *
     * @mbggenerated Thu Sep 26 10:37:52 CST 2013
     */
    int insertSelective(ExpressMessageDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table express_message
     *
     * @mbggenerated Thu Sep 26 10:37:52 CST 2013
     */
    ExpressMessageDO selectByPrimaryKey(Integer id);
    
    List<ExpressMessageDO> getAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table express_message
     *
     * @mbggenerated Thu Sep 26 10:37:52 CST 2013
     */
    int updateByPrimaryKeySelective(ExpressMessageDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table express_message
     *
     * @mbggenerated Thu Sep 26 10:37:52 CST 2013
     */
    int updateByPrimaryKey(ExpressMessageDO record);
}