package tushu.product.mapper;

import java.util.List;

import tushu.model.IndexShowTypeDO;

public interface IndexShowTypeDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table index_show_type
     *
     * @mbggenerated Tue Sep 10 10:18:11 CST 2013
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table index_show_type
     *
     * @mbggenerated Tue Sep 10 10:18:11 CST 2013
     */
    int insert(IndexShowTypeDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table index_show_type
     *
     * @mbggenerated Tue Sep 10 10:18:11 CST 2013
     */
    int insertSelective(IndexShowTypeDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table index_show_type
     *
     * @mbggenerated Tue Sep 10 10:18:11 CST 2013
     */
    IndexShowTypeDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table index_show_type
     *
     * @mbggenerated Tue Sep 10 10:18:11 CST 2013
     */
    int updateByPrimaryKeySelective(IndexShowTypeDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table index_show_type
     *
     * @mbggenerated Tue Sep 10 10:18:11 CST 2013
     */
    int updateByPrimaryKey(IndexShowTypeDO record);
    
    List<IndexShowTypeDO> selectBytype(String type);
}