package tushu.product.mapper;

import java.util.List;

import tushu.model.PageDO;

public interface PageDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table page_message
     *
     * @mbggenerated Thu Nov 07 15:46:39 CST 2013
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table page_message
     *
     * @mbggenerated Thu Nov 07 15:46:39 CST 2013
     */
    int insert(PageDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table page_message
     *
     * @mbggenerated Thu Nov 07 15:46:39 CST 2013
     */
    int insertSelective(PageDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table page_message
     *
     * @mbggenerated Thu Nov 07 15:46:39 CST 2013
     */
    PageDO selectByPrimaryKey(Integer id);
    
    List<PageDO> getByWorkId(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table page_message
     *
     * @mbggenerated Thu Nov 07 15:46:39 CST 2013
     */
    int updateByPrimaryKeySelective(PageDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table page_message
     *
     * @mbggenerated Thu Nov 07 15:46:39 CST 2013
     */
    int updateByPrimaryKey(PageDO record);
}