package tushu.product.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import tushu.model.ProductDO;

public interface ProductDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated Mon Sep 09 16:18:50 CST 2013
     */
    int deleteByPrimaryKey(Integer productId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated Mon Sep 09 16:18:50 CST 2013
     */
    int insert(ProductDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated Mon Sep 09 16:18:50 CST 2013
     */
    int insertSelective(ProductDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated Mon Sep 09 16:18:50 CST 2013
     */
    ProductDO selectByPrimaryKey(Integer productId);
    
    List<ProductDO> getByIndexShowType(Integer typeId);
    
    List<ProductDO> getByColumn(@Param("column") String column, @Param("size") Integer size);

    List<ProductDO> getAll();
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated Mon Sep 09 16:18:50 CST 2013
     */
    int updateByPrimaryKeySelective(ProductDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated Mon Sep 09 16:18:50 CST 2013
     */
    int updateByPrimaryKey(ProductDO record);
    
    int updateViewCount(@Param("productId") Integer productId, @Param("viewCount") Integer viewCount);
    
    int updateSaledCount(@Param("productId") Integer productId, @Param("saledCount") Integer saledCount);
}