package tushu.product.mapper;

import java.util.List;

import tushu.model.TemplateDO;

public interface TemplateDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table template
     *
     * @mbggenerated Fri Nov 01 13:53:51 CST 2013
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table template
     *
     * @mbggenerated Fri Nov 01 13:53:51 CST 2013
     */
    int insert(TemplateDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table template
     *
     * @mbggenerated Fri Nov 01 13:53:51 CST 2013
     */
    int insertSelective(TemplateDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table template
     *
     * @mbggenerated Fri Nov 01 13:53:51 CST 2013
     */
    TemplateDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table template
     *
     * @mbggenerated Fri Nov 01 13:53:51 CST 2013
     */
    int updateByPrimaryKeySelective(TemplateDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table template
     *
     * @mbggenerated Fri Nov 01 13:53:51 CST 2013
     */
    int updateByPrimaryKey(TemplateDO record);
    
    List<TemplateDO> getAll();
}