package tushu.product.mapper;

import tushu.model.WorkRelationshipImageDO;

public interface WorkRelationshipImageDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_relationship_image
     *
     * @mbggenerated Mon Oct 28 16:04:15 CST 2013
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_relationship_image
     *
     * @mbggenerated Mon Oct 28 16:04:15 CST 2013
     */
    int insert(WorkRelationshipImageDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_relationship_image
     *
     * @mbggenerated Mon Oct 28 16:04:15 CST 2013
     */
    int insertSelective(WorkRelationshipImageDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_relationship_image
     *
     * @mbggenerated Mon Oct 28 16:04:15 CST 2013
     */
    WorkRelationshipImageDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_relationship_image
     *
     * @mbggenerated Mon Oct 28 16:04:15 CST 2013
     */
    int updateByPrimaryKeySelective(WorkRelationshipImageDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_relationship_image
     *
     * @mbggenerated Mon Oct 28 16:04:15 CST 2013
     */
    int updateByPrimaryKey(WorkRelationshipImageDO record);
}