package tushu.product.mapper;

import java.util.List;

import tushu.model.WorkDO;

public interface WorkDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_message
     *
     * @mbggenerated Mon Oct 28 15:52:38 CST 2013
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_message
     *
     * @mbggenerated Mon Oct 28 15:52:38 CST 2013
     */
    int insert(WorkDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_message
     *
     * @mbggenerated Mon Oct 28 15:52:38 CST 2013
     */
    int insertSelective(WorkDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_message
     *
     * @mbggenerated Mon Oct 28 15:52:38 CST 2013
     */
    WorkDO selectByPrimaryKey(Integer id);
    
    List<WorkDO> getByUserId(Long userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_message
     *
     * @mbggenerated Mon Oct 28 15:52:38 CST 2013
     */
    int updateByPrimaryKeySelective(WorkDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_message
     *
     * @mbggenerated Mon Oct 28 15:52:38 CST 2013
     */
    int updateByPrimaryKey(WorkDO record);
}